//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Self_Love_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SelfLoveBDEntities : DbContext
    {
        public SelfLoveBDEntities()
            : base("name=SelfLoveBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<Emociones> Emociones { get; set; }
        public virtual DbSet<Habitos> Habitos { get; set; }
        public virtual DbSet<Publicaciones> Publicaciones { get; set; }
        public virtual DbSet<Recursos> Recursos { get; set; }
        public virtual DbSet<SeguimientoHabitos> SeguimientoHabitos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Psicologos> Psicologos { get; set; }
    }
}
