//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Self_Love_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Psicologos
    {
        public int PsicologoID { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public string Especialidad { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
