//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba_selflove
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SelfLoveEntities : DbContext
    {
        public SelfLoveEntities()
            : base("name=SelfLoveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Notificaciones> Notificaciones { get; set; }
        public DbSet<OpcionesRespuesta> OpcionesRespuesta { get; set; }
        public DbSet<Pacientes> Pacientes { get; set; }
        public DbSet<Pagos> Pagos { get; set; }
        public DbSet<PreguntasTest> PreguntasTest { get; set; }
        public DbSet<Sesiones> Sesiones { get; set; }
        public DbSet<Suscripciones> Suscripciones { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Terapeutas> Terapeutas { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
