//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba_selflove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public Pacientes()
        {
            this.Sesiones = new HashSet<Sesiones>();
        }
    
        public int PacienteId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Genero { get; set; }
        public string HistorialMedico { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Sesiones> Sesiones { get; set; }
    }
}
