//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba_selflove
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntasTest
    {
        public PreguntasTest()
        {
            this.OpcionesRespuesta = new HashSet<OpcionesRespuesta>();
        }
    
        public int PreguntaId { get; set; }
        public string TextoPregunta { get; set; }
        public string Categoria { get; set; }
    
        public virtual ICollection<OpcionesRespuesta> OpcionesRespuesta { get; set; }
    }
}
