//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba_selflove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones
    {
        public int SesionId { get; set; }
        public int PacienteId { get; set; }
        public int TerapeutaId { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int Duracion { get; set; }
        public string Estado { get; set; }
        public string EnlaceVideollamada { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
        public virtual Terapeutas Terapeutas { get; set; }
    }
}
