//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba_selflove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terapeutas
    {
        public Terapeutas()
        {
            this.Sesiones = new HashSet<Sesiones>();
        }
    
        public int TerapeutaId { get; set; }
        public int UsuarioId { get; set; }
        public string Especialidad { get; set; }
        public string Certificaciones { get; set; }
        public Nullable<int> Experiencia { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Sesiones> Sesiones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
