//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba_selflove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Notificaciones = new HashSet<Notificaciones>();
            this.Pacientes = new HashSet<Pacientes>();
            this.Pagos = new HashSet<Pagos>();
            this.Suscripciones = new HashSet<Suscripciones>();
            this.Terapeutas = new HashSet<Terapeutas>();
        }
    
        public int UsuarioId { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Correo { get; set; }
        public string ContrasenaHash { get; set; }
        public string Telefono { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        public virtual ICollection<Pacientes> Pacientes { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ICollection<Suscripciones> Suscripciones { get; set; }
        public virtual ICollection<Terapeutas> Terapeutas { get; set; }
    }
}
